/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Delivery {
  'arrivalTime' : bigint,
  'supplierName' : string,
  'productId' : string,
  'quantity' : bigint,
}
export interface Product {
  'id' : string,
  'name' : string,
  'sector' : string,
  'sellPrice' : number,
  'shelfLife' : bigint,
  'baseCost' : number,
}
export interface StockItem {
  'purchasePrice' : number,
  'sellingPrice' : number,
  'productId' : string,
  'expirationTime' : bigint,
  'quantity' : bigint,
}
export interface StoreSectorSnapshot {
  'name' : string,
  'qualityLevel' : bigint,
  'stock' : Array<StockItem>,
  'staffAssigned' : bigint,
  'cleanliness' : bigint,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'storeName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, number, number, string, bigint],
    undefined
  >,
  'addSector' : ActorMethod<[string], undefined>,
  'addSupplier' : ActorMethod<[string, number, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStore' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFunds' : ActorMethod<[], number>,
  'getPendingDeliveries' : ActorMethod<[], Array<Delivery>>,
  'getReputation' : ActorMethod<[], number>,
  'getSectors' : ActorMethod<[], Array<StoreSectorSnapshot>>,
  'getStoreProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'orderStock' : ActorMethod<[string, bigint, string], undefined>,
  'receiveDeliveries' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];