/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'storeName' : IDL.Text,
});
export const Delivery = IDL.Record({
  'arrivalTime' : IDL.Int,
  'supplierName' : IDL.Text,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const StockItem = IDL.Record({
  'purchasePrice' : IDL.Float64,
  'sellingPrice' : IDL.Float64,
  'productId' : IDL.Text,
  'expirationTime' : IDL.Int,
  'quantity' : IDL.Nat,
});
export const StoreSectorSnapshot = IDL.Record({
  'name' : IDL.Text,
  'qualityLevel' : IDL.Nat,
  'stock' : IDL.Vec(StockItem),
  'staffAssigned' : IDL.Nat,
  'cleanliness' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'sector' : IDL.Text,
  'sellPrice' : IDL.Float64,
  'shelfLife' : IDL.Nat,
  'baseCost' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addSector' : IDL.Func([IDL.Text], [], []),
  'addSupplier' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStore' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFunds' : IDL.Func([], [IDL.Float64], ['query']),
  'getPendingDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
  'getReputation' : IDL.Func([], [IDL.Float64], ['query']),
  'getSectors' : IDL.Func([], [IDL.Vec(StoreSectorSnapshot)], ['query']),
  'getStoreProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'orderStock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'receiveDeliveries' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'storeName' : IDL.Text,
  });
  const Delivery = IDL.Record({
    'arrivalTime' : IDL.Int,
    'supplierName' : IDL.Text,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const StockItem = IDL.Record({
    'purchasePrice' : IDL.Float64,
    'sellingPrice' : IDL.Float64,
    'productId' : IDL.Text,
    'expirationTime' : IDL.Int,
    'quantity' : IDL.Nat,
  });
  const StoreSectorSnapshot = IDL.Record({
    'name' : IDL.Text,
    'qualityLevel' : IDL.Nat,
    'stock' : IDL.Vec(StockItem),
    'staffAssigned' : IDL.Nat,
    'cleanliness' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'sector' : IDL.Text,
    'sellPrice' : IDL.Float64,
    'shelfLife' : IDL.Nat,
    'baseCost' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addSector' : IDL.Func([IDL.Text], [], []),
    'addSupplier' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStore' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFunds' : IDL.Func([], [IDL.Float64], ['query']),
    'getPendingDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
    'getReputation' : IDL.Func([], [IDL.Float64], ['query']),
    'getSectors' : IDL.Func([], [IDL.Vec(StoreSectorSnapshot)], ['query']),
    'getStoreProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'orderStock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'receiveDeliveries' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };